#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="gorselegitim_org")]
public partial class eticaretDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertYorumlar(Yorumlar instance);
  partial void UpdateYorumlar(Yorumlar instance);
  partial void DeleteYorumlar(Yorumlar instance);
  partial void InsertVitrin(Vitrin instance);
  partial void UpdateVitrin(Vitrin instance);
  partial void DeleteVitrin(Vitrin instance);
  partial void InsertUyeler(Uyeler instance);
  partial void UpdateUyeler(Uyeler instance);
  partial void DeleteUyeler(Uyeler instance);
  partial void InsertUrunler(Urunler instance);
  partial void UpdateUrunler(Urunler instance);
  partial void DeleteUrunler(Urunler instance);
  partial void InsertSepet(Sepet instance);
  partial void UpdateSepet(Sepet instance);
  partial void DeleteSepet(Sepet instance);
  partial void InsertMarkalar(Markalar instance);
  partial void UpdateMarkalar(Markalar instance);
  partial void DeleteMarkalar(Markalar instance);
  partial void InsertKargolar(Kargolar instance);
  partial void UpdateKargolar(Kargolar instance);
  partial void DeleteKargolar(Kargolar instance);
  partial void Inserthesapnumaralari(hesapnumaralari instance);
  partial void Updatehesapnumaralari(hesapnumaralari instance);
  partial void Deletehesapnumaralari(hesapnumaralari instance);
  partial void InsertAnaKategoriler(AnaKategoriler instance);
  partial void UpdateAnaKategoriler(AnaKategoriler instance);
  partial void DeleteAnaKategoriler(AnaKategoriler instance);
  partial void InsertAltKategoriler(AltKategoriler instance);
  partial void UpdateAltKategoriler(AltKategoriler instance);
  partial void DeleteAltKategoriler(AltKategoriler instance);
  #endregion
	
	public eticaretDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["gorselegitim_orgConnectionString2"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public eticaretDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public eticaretDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public eticaretDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public eticaretDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Yorumlar> Yorumlars
	{
		get
		{
			return this.GetTable<Yorumlar>();
		}
	}
	
	public System.Data.Linq.Table<Vitrin> Vitrins
	{
		get
		{
			return this.GetTable<Vitrin>();
		}
	}
	
	public System.Data.Linq.Table<Uyeler> Uyelers
	{
		get
		{
			return this.GetTable<Uyeler>();
		}
	}
	
	public System.Data.Linq.Table<Urunler> Urunlers
	{
		get
		{
			return this.GetTable<Urunler>();
		}
	}
	
	public System.Data.Linq.Table<Sepet> Sepets
	{
		get
		{
			return this.GetTable<Sepet>();
		}
	}
	
	public System.Data.Linq.Table<Markalar> Markalars
	{
		get
		{
			return this.GetTable<Markalar>();
		}
	}
	
	public System.Data.Linq.Table<Kargolar> Kargolars
	{
		get
		{
			return this.GetTable<Kargolar>();
		}
	}
	
	public System.Data.Linq.Table<hesapnumaralari> hesapnumaralaris
	{
		get
		{
			return this.GetTable<hesapnumaralari>();
		}
	}
	
	public System.Data.Linq.Table<AnaKategoriler> AnaKategorilers
	{
		get
		{
			return this.GetTable<AnaKategoriler>();
		}
	}
	
	public System.Data.Linq.Table<AltKategoriler> AltKategorilers
	{
		get
		{
			return this.GetTable<AltKategoriler>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sepeteekle")]
	public int sepeteekle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UyeID", DbType="Int")] System.Nullable<int> uyeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UrunID", DbType="Int")] System.Nullable<int> urunID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EklemeTarihi", DbType="SmallDateTime")] System.Nullable<System.DateTime> eklemeTarihi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adet", DbType="Int")] System.Nullable<int> adet)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uyeID, urunID, eklemeTarihi, adet);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sepetgetir")]
	public ISingleResult<sepetgetirResult> sepetgetir([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UyeID", DbType="Int")] System.Nullable<int> uyeID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uyeID);
		return ((ISingleResult<sepetgetirResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sepetguncelle")]
	public int sepetguncelle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SepetID", DbType="Int")] System.Nullable<int> sepetID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adet", DbType="Int")] System.Nullable<int> adet)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sepetID, adet);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sepetsil")]
	public int Sepetsil([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SepetID", DbType="Int")] System.Nullable<int> sepetID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sepetID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.urunguncelle")]
	public int urunguncelle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UrunID", DbType="Int")] System.Nullable<int> urunID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UrunAd", DbType="NVarChar(150)")] string urunAd, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UrunDetay", DbType="NVarChar(MAX)")] string urunDetay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UrunFiyat", DbType="Money")] System.Nullable<decimal> urunFiyat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Kdv", DbType="Money")] System.Nullable<decimal> kdv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> indirim, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Taksit", DbType="NVarChar(MAX)")] string taksit, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resim1", DbType="NVarChar(50)")] string resim1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resim2", DbType="NVarChar(50)")] string resim2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resim3", DbType="NVarChar(50)")] string resim3, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Video", DbType="NVarChar(50)")] string video, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AKID", DbType="Int")] System.Nullable<int> aKID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ALTID", DbType="Int")] System.Nullable<int> aLTID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MarkaID", DbType="Int")] System.Nullable<int> markaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="YayinDurumu", DbType="Bit")] System.Nullable<bool> yayinDurumu)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), urunID, urunAd, urunDetay, urunFiyat, kdv, indirim, taksit, resim1, resim2, resim3, video, aKID, aLTID, markaID, yayinDurumu);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UyeKontrol")]
	public ISingleResult<UyeKontrolResult> UyeKontrol([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UyeEposta", DbType="NVarChar(50)")] string uyeEposta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sifre", DbType="NVarChar(41)")] string sifre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Onay", DbType="Int")] System.Nullable<int> onay)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uyeEposta, sifre, onay);
		return ((ISingleResult<UyeKontrolResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UyeleriGetir")]
	public ISingleResult<UyeleriGetirResult> UyeleriGetir()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<UyeleriGetirResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VitrinEkle")]
	public int VitrinEkle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VitrinResim", DbType="NVarChar(150)")] string vitrinResim, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VitrinUrl", DbType="NVarChar(250)")] string vitrinUrl)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), vitrinResim, vitrinUrl);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VitrinGetir")]
	public ISingleResult<VitrinGetirResult> VitrinGetir()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<VitrinGetirResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VitrinSil")]
	public int VitrinSil([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Yorumlar")]
public partial class Yorumlar : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _YorumID;
	
	private System.Nullable<int> _urunad;
	
	private string _Baslik;
	
	private string _Yorum;
	
	private System.Nullable<int> _Durum;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYorumIDChanging(int value);
    partial void OnYorumIDChanged();
    partial void OnurunadChanging(System.Nullable<int> value);
    partial void OnurunadChanged();
    partial void OnBaslikChanging(string value);
    partial void OnBaslikChanged();
    partial void OnYorumChanging(string value);
    partial void OnYorumChanged();
    partial void OnDurumChanging(System.Nullable<int> value);
    partial void OnDurumChanged();
    #endregion
	
	public Yorumlar()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YorumID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int YorumID
	{
		get
		{
			return this._YorumID;
		}
		set
		{
			if ((this._YorumID != value))
			{
				this.OnYorumIDChanging(value);
				this.SendPropertyChanging();
				this._YorumID = value;
				this.SendPropertyChanged("YorumID");
				this.OnYorumIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urunad", DbType="Int")]
	public System.Nullable<int> urunad
	{
		get
		{
			return this._urunad;
		}
		set
		{
			if ((this._urunad != value))
			{
				this.OnurunadChanging(value);
				this.SendPropertyChanging();
				this._urunad = value;
				this.SendPropertyChanged("urunad");
				this.OnurunadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Baslik", DbType="NVarChar(150)")]
	public string Baslik
	{
		get
		{
			return this._Baslik;
		}
		set
		{
			if ((this._Baslik != value))
			{
				this.OnBaslikChanging(value);
				this.SendPropertyChanging();
				this._Baslik = value;
				this.SendPropertyChanged("Baslik");
				this.OnBaslikChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yorum", DbType="NVarChar(MAX)")]
	public string Yorum
	{
		get
		{
			return this._Yorum;
		}
		set
		{
			if ((this._Yorum != value))
			{
				this.OnYorumChanging(value);
				this.SendPropertyChanging();
				this._Yorum = value;
				this.SendPropertyChanged("Yorum");
				this.OnYorumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Durum", DbType="Int")]
	public System.Nullable<int> Durum
	{
		get
		{
			return this._Durum;
		}
		set
		{
			if ((this._Durum != value))
			{
				this.OnDurumChanging(value);
				this.SendPropertyChanging();
				this._Durum = value;
				this.SendPropertyChanged("Durum");
				this.OnDurumChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vitrin")]
public partial class Vitrin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _VitrinResim;
	
	private string _VitrinUrl;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnVitrinResimChanging(string value);
    partial void OnVitrinResimChanged();
    partial void OnVitrinUrlChanging(string value);
    partial void OnVitrinUrlChanged();
    #endregion
	
	public Vitrin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VitrinResim", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string VitrinResim
	{
		get
		{
			return this._VitrinResim;
		}
		set
		{
			if ((this._VitrinResim != value))
			{
				this.OnVitrinResimChanging(value);
				this.SendPropertyChanging();
				this._VitrinResim = value;
				this.SendPropertyChanged("VitrinResim");
				this.OnVitrinResimChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VitrinUrl", DbType="NVarChar(150)")]
	public string VitrinUrl
	{
		get
		{
			return this._VitrinUrl;
		}
		set
		{
			if ((this._VitrinUrl != value))
			{
				this.OnVitrinUrlChanging(value);
				this.SendPropertyChanging();
				this._VitrinUrl = value;
				this.SendPropertyChanged("VitrinUrl");
				this.OnVitrinUrlChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uyeler")]
public partial class Uyeler : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _UyeID;
	
	private string _UyeAdSoyad;
	
	private string _UyeEposta;
	
	private string _Sifre;
	
	private string _Adres;
	
	private string _Telefon;
	
	private string _Gsm;
	
	private System.Nullable<System.DateTime> _EklemeTarihi;
	
	private System.Nullable<int> _Onay;
	
	private string _Sehir;
	
	private string _Ilce;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUyeIDChanging(int value);
    partial void OnUyeIDChanged();
    partial void OnUyeAdSoyadChanging(string value);
    partial void OnUyeAdSoyadChanged();
    partial void OnUyeEpostaChanging(string value);
    partial void OnUyeEpostaChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnGsmChanging(string value);
    partial void OnGsmChanged();
    partial void OnEklemeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnEklemeTarihiChanged();
    partial void OnOnayChanging(System.Nullable<int> value);
    partial void OnOnayChanged();
    partial void OnSehirChanging(string value);
    partial void OnSehirChanged();
    partial void OnIlceChanging(string value);
    partial void OnIlceChanged();
    #endregion
	
	public Uyeler()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int UyeID
	{
		get
		{
			return this._UyeID;
		}
		set
		{
			if ((this._UyeID != value))
			{
				this.OnUyeIDChanging(value);
				this.SendPropertyChanging();
				this._UyeID = value;
				this.SendPropertyChanged("UyeID");
				this.OnUyeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyeAdSoyad", DbType="NVarChar(100)")]
	public string UyeAdSoyad
	{
		get
		{
			return this._UyeAdSoyad;
		}
		set
		{
			if ((this._UyeAdSoyad != value))
			{
				this.OnUyeAdSoyadChanging(value);
				this.SendPropertyChanging();
				this._UyeAdSoyad = value;
				this.SendPropertyChanged("UyeAdSoyad");
				this.OnUyeAdSoyadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyeEposta", DbType="NVarChar(50)")]
	public string UyeEposta
	{
		get
		{
			return this._UyeEposta;
		}
		set
		{
			if ((this._UyeEposta != value))
			{
				this.OnUyeEpostaChanging(value);
				this.SendPropertyChanging();
				this._UyeEposta = value;
				this.SendPropertyChanged("UyeEposta");
				this.OnUyeEpostaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(41)")]
	public string Sifre
	{
		get
		{
			return this._Sifre;
		}
		set
		{
			if ((this._Sifre != value))
			{
				this.OnSifreChanging(value);
				this.SendPropertyChanging();
				this._Sifre = value;
				this.SendPropertyChanged("Sifre");
				this.OnSifreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(MAX)")]
	public string Adres
	{
		get
		{
			return this._Adres;
		}
		set
		{
			if ((this._Adres != value))
			{
				this.OnAdresChanging(value);
				this.SendPropertyChanging();
				this._Adres = value;
				this.SendPropertyChanged("Adres");
				this.OnAdresChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="Char(11)")]
	public string Telefon
	{
		get
		{
			return this._Telefon;
		}
		set
		{
			if ((this._Telefon != value))
			{
				this.OnTelefonChanging(value);
				this.SendPropertyChanging();
				this._Telefon = value;
				this.SendPropertyChanged("Telefon");
				this.OnTelefonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gsm", DbType="Char(11)")]
	public string Gsm
	{
		get
		{
			return this._Gsm;
		}
		set
		{
			if ((this._Gsm != value))
			{
				this.OnGsmChanging(value);
				this.SendPropertyChanging();
				this._Gsm = value;
				this.SendPropertyChanged("Gsm");
				this.OnGsmChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EklemeTarihi", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> EklemeTarihi
	{
		get
		{
			return this._EklemeTarihi;
		}
		set
		{
			if ((this._EklemeTarihi != value))
			{
				this.OnEklemeTarihiChanging(value);
				this.SendPropertyChanging();
				this._EklemeTarihi = value;
				this.SendPropertyChanged("EklemeTarihi");
				this.OnEklemeTarihiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Onay", DbType="Int")]
	public System.Nullable<int> Onay
	{
		get
		{
			return this._Onay;
		}
		set
		{
			if ((this._Onay != value))
			{
				this.OnOnayChanging(value);
				this.SendPropertyChanging();
				this._Onay = value;
				this.SendPropertyChanged("Onay");
				this.OnOnayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sehir", DbType="NVarChar(50)")]
	public string Sehir
	{
		get
		{
			return this._Sehir;
		}
		set
		{
			if ((this._Sehir != value))
			{
				this.OnSehirChanging(value);
				this.SendPropertyChanging();
				this._Sehir = value;
				this.SendPropertyChanged("Sehir");
				this.OnSehirChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilce", DbType="NVarChar(50)")]
	public string Ilce
	{
		get
		{
			return this._Ilce;
		}
		set
		{
			if ((this._Ilce != value))
			{
				this.OnIlceChanging(value);
				this.SendPropertyChanging();
				this._Ilce = value;
				this.SendPropertyChanged("Ilce");
				this.OnIlceChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Urunler")]
public partial class Urunler : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _UrunID;
	
	private string _UrunAd;
	
	private string _UrunDetay;
	
	private decimal _UrunFiyat;
	
	private System.Nullable<decimal> _Kdv;
	
	private System.Nullable<bool> _indirim;
	
	private string _Taksit;
	
	private System.Nullable<System.DateTime> _EklenmeTarihi;
	
	private System.Nullable<int> _Okunma;
	
	private string _Resim1;
	
	private string _Resim2;
	
	private string _Resim3;
	
	private string _Video;
	
	private int _AKID;
	
	private int _ALTID;
	
	private int _MarkaID;
	
	private System.Nullable<bool> _YayinDumu;
	
	private System.Nullable<int> _Puan;
	
	private EntityRef<Markalar> _Markalar;
	
	private EntityRef<AnaKategoriler> _AnaKategoriler;
	
	private EntityRef<AltKategoriler> _AltKategoriler;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUrunIDChanging(int value);
    partial void OnUrunIDChanged();
    partial void OnUrunAdChanging(string value);
    partial void OnUrunAdChanged();
    partial void OnUrunDetayChanging(string value);
    partial void OnUrunDetayChanged();
    partial void OnUrunFiyatChanging(decimal value);
    partial void OnUrunFiyatChanged();
    partial void OnKdvChanging(System.Nullable<decimal> value);
    partial void OnKdvChanged();
    partial void OnindirimChanging(System.Nullable<bool> value);
    partial void OnindirimChanged();
    partial void OnTaksitChanging(string value);
    partial void OnTaksitChanged();
    partial void OnEklenmeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnEklenmeTarihiChanged();
    partial void OnOkunmaChanging(System.Nullable<int> value);
    partial void OnOkunmaChanged();
    partial void OnResim1Changing(string value);
    partial void OnResim1Changed();
    partial void OnResim2Changing(string value);
    partial void OnResim2Changed();
    partial void OnResim3Changing(string value);
    partial void OnResim3Changed();
    partial void OnVideoChanging(string value);
    partial void OnVideoChanged();
    partial void OnAKIDChanging(int value);
    partial void OnAKIDChanged();
    partial void OnALTIDChanging(int value);
    partial void OnALTIDChanged();
    partial void OnMarkaIDChanging(int value);
    partial void OnMarkaIDChanged();
    partial void OnYayinDumuChanging(System.Nullable<bool> value);
    partial void OnYayinDumuChanged();
    partial void OnPuanChanging(System.Nullable<int> value);
    partial void OnPuanChanged();
    #endregion
	
	public Urunler()
	{
		this._Markalar = default(EntityRef<Markalar>);
		this._AnaKategoriler = default(EntityRef<AnaKategoriler>);
		this._AltKategoriler = default(EntityRef<AltKategoriler>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int UrunID
	{
		get
		{
			return this._UrunID;
		}
		set
		{
			if ((this._UrunID != value))
			{
				this.OnUrunIDChanging(value);
				this.SendPropertyChanging();
				this._UrunID = value;
				this.SendPropertyChanged("UrunID");
				this.OnUrunIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAd", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string UrunAd
	{
		get
		{
			return this._UrunAd;
		}
		set
		{
			if ((this._UrunAd != value))
			{
				this.OnUrunAdChanging(value);
				this.SendPropertyChanging();
				this._UrunAd = value;
				this.SendPropertyChanged("UrunAd");
				this.OnUrunAdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunDetay", DbType="NVarChar(MAX)")]
	public string UrunDetay
	{
		get
		{
			return this._UrunDetay;
		}
		set
		{
			if ((this._UrunDetay != value))
			{
				this.OnUrunDetayChanging(value);
				this.SendPropertyChanging();
				this._UrunDetay = value;
				this.SendPropertyChanged("UrunDetay");
				this.OnUrunDetayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunFiyat", DbType="Money NOT NULL")]
	public decimal UrunFiyat
	{
		get
		{
			return this._UrunFiyat;
		}
		set
		{
			if ((this._UrunFiyat != value))
			{
				this.OnUrunFiyatChanging(value);
				this.SendPropertyChanging();
				this._UrunFiyat = value;
				this.SendPropertyChanged("UrunFiyat");
				this.OnUrunFiyatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kdv", DbType="Money")]
	public System.Nullable<decimal> Kdv
	{
		get
		{
			return this._Kdv;
		}
		set
		{
			if ((this._Kdv != value))
			{
				this.OnKdvChanging(value);
				this.SendPropertyChanging();
				this._Kdv = value;
				this.SendPropertyChanged("Kdv");
				this.OnKdvChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indirim", DbType="Bit")]
	public System.Nullable<bool> indirim
	{
		get
		{
			return this._indirim;
		}
		set
		{
			if ((this._indirim != value))
			{
				this.OnindirimChanging(value);
				this.SendPropertyChanging();
				this._indirim = value;
				this.SendPropertyChanged("indirim");
				this.OnindirimChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taksit", DbType="NVarChar(MAX)")]
	public string Taksit
	{
		get
		{
			return this._Taksit;
		}
		set
		{
			if ((this._Taksit != value))
			{
				this.OnTaksitChanging(value);
				this.SendPropertyChanging();
				this._Taksit = value;
				this.SendPropertyChanged("Taksit");
				this.OnTaksitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EklenmeTarihi", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> EklenmeTarihi
	{
		get
		{
			return this._EklenmeTarihi;
		}
		set
		{
			if ((this._EklenmeTarihi != value))
			{
				this.OnEklenmeTarihiChanging(value);
				this.SendPropertyChanging();
				this._EklenmeTarihi = value;
				this.SendPropertyChanged("EklenmeTarihi");
				this.OnEklenmeTarihiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Okunma", DbType="Int")]
	public System.Nullable<int> Okunma
	{
		get
		{
			return this._Okunma;
		}
		set
		{
			if ((this._Okunma != value))
			{
				this.OnOkunmaChanging(value);
				this.SendPropertyChanging();
				this._Okunma = value;
				this.SendPropertyChanged("Okunma");
				this.OnOkunmaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim1", DbType="NVarChar(50)")]
	public string Resim1
	{
		get
		{
			return this._Resim1;
		}
		set
		{
			if ((this._Resim1 != value))
			{
				this.OnResim1Changing(value);
				this.SendPropertyChanging();
				this._Resim1 = value;
				this.SendPropertyChanged("Resim1");
				this.OnResim1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim2", DbType="NVarChar(50)")]
	public string Resim2
	{
		get
		{
			return this._Resim2;
		}
		set
		{
			if ((this._Resim2 != value))
			{
				this.OnResim2Changing(value);
				this.SendPropertyChanging();
				this._Resim2 = value;
				this.SendPropertyChanged("Resim2");
				this.OnResim2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim3", DbType="NVarChar(50)")]
	public string Resim3
	{
		get
		{
			return this._Resim3;
		}
		set
		{
			if ((this._Resim3 != value))
			{
				this.OnResim3Changing(value);
				this.SendPropertyChanging();
				this._Resim3 = value;
				this.SendPropertyChanged("Resim3");
				this.OnResim3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Video", DbType="NVarChar(50)")]
	public string Video
	{
		get
		{
			return this._Video;
		}
		set
		{
			if ((this._Video != value))
			{
				this.OnVideoChanging(value);
				this.SendPropertyChanging();
				this._Video = value;
				this.SendPropertyChanged("Video");
				this.OnVideoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKID", DbType="Int NOT NULL")]
	public int AKID
	{
		get
		{
			return this._AKID;
		}
		set
		{
			if ((this._AKID != value))
			{
				if (this._AnaKategoriler.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnAKIDChanging(value);
				this.SendPropertyChanging();
				this._AKID = value;
				this.SendPropertyChanged("AKID");
				this.OnAKIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTID", DbType="Int NOT NULL")]
	public int ALTID
	{
		get
		{
			return this._ALTID;
		}
		set
		{
			if ((this._ALTID != value))
			{
				if (this._AltKategoriler.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnALTIDChanging(value);
				this.SendPropertyChanging();
				this._ALTID = value;
				this.SendPropertyChanged("ALTID");
				this.OnALTIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaID", DbType="Int NOT NULL")]
	public int MarkaID
	{
		get
		{
			return this._MarkaID;
		}
		set
		{
			if ((this._MarkaID != value))
			{
				if (this._Markalar.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMarkaIDChanging(value);
				this.SendPropertyChanging();
				this._MarkaID = value;
				this.SendPropertyChanged("MarkaID");
				this.OnMarkaIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YayinDumu", DbType="Bit")]
	public System.Nullable<bool> YayinDumu
	{
		get
		{
			return this._YayinDumu;
		}
		set
		{
			if ((this._YayinDumu != value))
			{
				this.OnYayinDumuChanging(value);
				this.SendPropertyChanging();
				this._YayinDumu = value;
				this.SendPropertyChanged("YayinDumu");
				this.OnYayinDumuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puan", DbType="Int")]
	public System.Nullable<int> Puan
	{
		get
		{
			return this._Puan;
		}
		set
		{
			if ((this._Puan != value))
			{
				this.OnPuanChanging(value);
				this.SendPropertyChanging();
				this._Puan = value;
				this.SendPropertyChanged("Puan");
				this.OnPuanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Markalar_Urunler", Storage="_Markalar", ThisKey="MarkaID", OtherKey="MarkID", IsForeignKey=true)]
	public Markalar Markalar
	{
		get
		{
			return this._Markalar.Entity;
		}
		set
		{
			Markalar previousValue = this._Markalar.Entity;
			if (((previousValue != value) 
						|| (this._Markalar.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Markalar.Entity = null;
					previousValue.Urunlers.Remove(this);
				}
				this._Markalar.Entity = value;
				if ((value != null))
				{
					value.Urunlers.Add(this);
					this._MarkaID = value.MarkID;
				}
				else
				{
					this._MarkaID = default(int);
				}
				this.SendPropertyChanged("Markalar");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AnaKategoriler_Urunler", Storage="_AnaKategoriler", ThisKey="AKID", OtherKey="AKID", IsForeignKey=true)]
	public AnaKategoriler AnaKategoriler
	{
		get
		{
			return this._AnaKategoriler.Entity;
		}
		set
		{
			AnaKategoriler previousValue = this._AnaKategoriler.Entity;
			if (((previousValue != value) 
						|| (this._AnaKategoriler.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._AnaKategoriler.Entity = null;
					previousValue.Urunlers.Remove(this);
				}
				this._AnaKategoriler.Entity = value;
				if ((value != null))
				{
					value.Urunlers.Add(this);
					this._AKID = value.AKID;
				}
				else
				{
					this._AKID = default(int);
				}
				this.SendPropertyChanged("AnaKategoriler");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AltKategoriler_Urunler", Storage="_AltKategoriler", ThisKey="ALTID", OtherKey="ALTID", IsForeignKey=true)]
	public AltKategoriler AltKategoriler
	{
		get
		{
			return this._AltKategoriler.Entity;
		}
		set
		{
			AltKategoriler previousValue = this._AltKategoriler.Entity;
			if (((previousValue != value) 
						|| (this._AltKategoriler.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._AltKategoriler.Entity = null;
					previousValue.Urunlers.Remove(this);
				}
				this._AltKategoriler.Entity = value;
				if ((value != null))
				{
					value.Urunlers.Add(this);
					this._ALTID = value.ALTID;
				}
				else
				{
					this._ALTID = default(int);
				}
				this.SendPropertyChanged("AltKategoriler");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sepet")]
public partial class Sepet : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _SepetID;
	
	private System.Nullable<int> _UyeID;
	
	private System.Nullable<int> _UrunID;
	
	private System.Nullable<System.DateTime> _EklemeTarihi;
	
	private System.Nullable<int> _Adet;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSepetIDChanging(int value);
    partial void OnSepetIDChanged();
    partial void OnUyeIDChanging(System.Nullable<int> value);
    partial void OnUyeIDChanged();
    partial void OnUrunIDChanging(System.Nullable<int> value);
    partial void OnUrunIDChanged();
    partial void OnEklemeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnEklemeTarihiChanged();
    partial void OnAdetChanging(System.Nullable<int> value);
    partial void OnAdetChanged();
    #endregion
	
	public Sepet()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SepetID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int SepetID
	{
		get
		{
			return this._SepetID;
		}
		set
		{
			if ((this._SepetID != value))
			{
				this.OnSepetIDChanging(value);
				this.SendPropertyChanging();
				this._SepetID = value;
				this.SendPropertyChanged("SepetID");
				this.OnSepetIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyeID", DbType="Int")]
	public System.Nullable<int> UyeID
	{
		get
		{
			return this._UyeID;
		}
		set
		{
			if ((this._UyeID != value))
			{
				this.OnUyeIDChanging(value);
				this.SendPropertyChanging();
				this._UyeID = value;
				this.SendPropertyChanged("UyeID");
				this.OnUyeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunID", DbType="Int")]
	public System.Nullable<int> UrunID
	{
		get
		{
			return this._UrunID;
		}
		set
		{
			if ((this._UrunID != value))
			{
				this.OnUrunIDChanging(value);
				this.SendPropertyChanging();
				this._UrunID = value;
				this.SendPropertyChanged("UrunID");
				this.OnUrunIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EklemeTarihi", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> EklemeTarihi
	{
		get
		{
			return this._EklemeTarihi;
		}
		set
		{
			if ((this._EklemeTarihi != value))
			{
				this.OnEklemeTarihiChanging(value);
				this.SendPropertyChanging();
				this._EklemeTarihi = value;
				this.SendPropertyChanged("EklemeTarihi");
				this.OnEklemeTarihiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adet", DbType="Int")]
	public System.Nullable<int> Adet
	{
		get
		{
			return this._Adet;
		}
		set
		{
			if ((this._Adet != value))
			{
				this.OnAdetChanging(value);
				this.SendPropertyChanging();
				this._Adet = value;
				this.SendPropertyChanged("Adet");
				this.OnAdetChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Markalar")]
public partial class Markalar : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MarkID;
	
	private string _MarkaAd;
	
	private int _ALTID;
	
	private EntitySet<Urunler> _Urunlers;
	
	private EntityRef<AltKategoriler> _AltKategoriler;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMarkIDChanging(int value);
    partial void OnMarkIDChanged();
    partial void OnMarkaAdChanging(string value);
    partial void OnMarkaAdChanged();
    partial void OnALTIDChanging(int value);
    partial void OnALTIDChanged();
    #endregion
	
	public Markalar()
	{
		this._Urunlers = new EntitySet<Urunler>(new Action<Urunler>(this.attach_Urunlers), new Action<Urunler>(this.detach_Urunlers));
		this._AltKategoriler = default(EntityRef<AltKategoriler>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MarkID
	{
		get
		{
			return this._MarkID;
		}
		set
		{
			if ((this._MarkID != value))
			{
				this.OnMarkIDChanging(value);
				this.SendPropertyChanging();
				this._MarkID = value;
				this.SendPropertyChanged("MarkID");
				this.OnMarkIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaAd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string MarkaAd
	{
		get
		{
			return this._MarkaAd;
		}
		set
		{
			if ((this._MarkaAd != value))
			{
				this.OnMarkaAdChanging(value);
				this.SendPropertyChanging();
				this._MarkaAd = value;
				this.SendPropertyChanged("MarkaAd");
				this.OnMarkaAdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTID", DbType="Int NOT NULL")]
	public int ALTID
	{
		get
		{
			return this._ALTID;
		}
		set
		{
			if ((this._ALTID != value))
			{
				if (this._AltKategoriler.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnALTIDChanging(value);
				this.SendPropertyChanging();
				this._ALTID = value;
				this.SendPropertyChanged("ALTID");
				this.OnALTIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Markalar_Urunler", Storage="_Urunlers", ThisKey="MarkID", OtherKey="MarkaID")]
	public EntitySet<Urunler> Urunlers
	{
		get
		{
			return this._Urunlers;
		}
		set
		{
			this._Urunlers.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AltKategoriler_Markalar", Storage="_AltKategoriler", ThisKey="ALTID", OtherKey="ALTID", IsForeignKey=true)]
	public AltKategoriler AltKategoriler
	{
		get
		{
			return this._AltKategoriler.Entity;
		}
		set
		{
			AltKategoriler previousValue = this._AltKategoriler.Entity;
			if (((previousValue != value) 
						|| (this._AltKategoriler.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._AltKategoriler.Entity = null;
					previousValue.Markalars.Remove(this);
				}
				this._AltKategoriler.Entity = value;
				if ((value != null))
				{
					value.Markalars.Add(this);
					this._ALTID = value.ALTID;
				}
				else
				{
					this._ALTID = default(int);
				}
				this.SendPropertyChanged("AltKategoriler");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Urunlers(Urunler entity)
	{
		this.SendPropertyChanging();
		entity.Markalar = this;
	}
	
	private void detach_Urunlers(Urunler entity)
	{
		this.SendPropertyChanging();
		entity.Markalar = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kargolar")]
public partial class Kargolar : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _KargoAdi;
	
	private System.Nullable<decimal> _Fiyat;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKargoAdiChanging(string value);
    partial void OnKargoAdiChanged();
    partial void OnFiyatChanging(System.Nullable<decimal> value);
    partial void OnFiyatChanged();
    #endregion
	
	public Kargolar()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KargoAdi", DbType="NVarChar(100)")]
	public string KargoAdi
	{
		get
		{
			return this._KargoAdi;
		}
		set
		{
			if ((this._KargoAdi != value))
			{
				this.OnKargoAdiChanging(value);
				this.SendPropertyChanging();
				this._KargoAdi = value;
				this.SendPropertyChanged("KargoAdi");
				this.OnKargoAdiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fiyat", DbType="Money")]
	public System.Nullable<decimal> Fiyat
	{
		get
		{
			return this._Fiyat;
		}
		set
		{
			if ((this._Fiyat != value))
			{
				this.OnFiyatChanging(value);
				this.SendPropertyChanging();
				this._Fiyat = value;
				this.SendPropertyChanged("Fiyat");
				this.OnFiyatChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hesapnumaralari")]
public partial class hesapnumaralari : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Banka;
	
	private string _SubeAdı;
	
	private string _SubeKodu;
	
	private string _HesapTuru;
	
	private string _HesapNo;
	
	private string _IBAn;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBankaChanging(string value);
    partial void OnBankaChanged();
    partial void OnSubeAdıChanging(string value);
    partial void OnSubeAdıChanged();
    partial void OnSubeKoduChanging(string value);
    partial void OnSubeKoduChanged();
    partial void OnHesapTuruChanging(string value);
    partial void OnHesapTuruChanged();
    partial void OnHesapNoChanging(string value);
    partial void OnHesapNoChanged();
    partial void OnIBAnChanging(string value);
    partial void OnIBAnChanged();
    #endregion
	
	public hesapnumaralari()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Banka", DbType="NVarChar(255)")]
	public string Banka
	{
		get
		{
			return this._Banka;
		}
		set
		{
			if ((this._Banka != value))
			{
				this.OnBankaChanging(value);
				this.SendPropertyChanging();
				this._Banka = value;
				this.SendPropertyChanged("Banka");
				this.OnBankaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubeAdı", DbType="NVarChar(255)")]
	public string SubeAdı
	{
		get
		{
			return this._SubeAdı;
		}
		set
		{
			if ((this._SubeAdı != value))
			{
				this.OnSubeAdıChanging(value);
				this.SendPropertyChanging();
				this._SubeAdı = value;
				this.SendPropertyChanged("SubeAdı");
				this.OnSubeAdıChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubeKodu", DbType="NVarChar(50)")]
	public string SubeKodu
	{
		get
		{
			return this._SubeKodu;
		}
		set
		{
			if ((this._SubeKodu != value))
			{
				this.OnSubeKoduChanging(value);
				this.SendPropertyChanging();
				this._SubeKodu = value;
				this.SendPropertyChanged("SubeKodu");
				this.OnSubeKoduChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HesapTuru", DbType="Char(10)")]
	public string HesapTuru
	{
		get
		{
			return this._HesapTuru;
		}
		set
		{
			if ((this._HesapTuru != value))
			{
				this.OnHesapTuruChanging(value);
				this.SendPropertyChanging();
				this._HesapTuru = value;
				this.SendPropertyChanged("HesapTuru");
				this.OnHesapTuruChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HesapNo", DbType="NVarChar(255)")]
	public string HesapNo
	{
		get
		{
			return this._HesapNo;
		}
		set
		{
			if ((this._HesapNo != value))
			{
				this.OnHesapNoChanging(value);
				this.SendPropertyChanging();
				this._HesapNo = value;
				this.SendPropertyChanged("HesapNo");
				this.OnHesapNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBAn", DbType="NVarChar(255)")]
	public string IBAn
	{
		get
		{
			return this._IBAn;
		}
		set
		{
			if ((this._IBAn != value))
			{
				this.OnIBAnChanging(value);
				this.SendPropertyChanging();
				this._IBAn = value;
				this.SendPropertyChanged("IBAn");
				this.OnIBAnChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AnaKategoriler")]
public partial class AnaKategoriler : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _AKID;
	
	private string _AKAD;
	
	private EntitySet<Urunler> _Urunlers;
	
	private EntitySet<AltKategoriler> _AltKategorilers;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAKIDChanging(int value);
    partial void OnAKIDChanged();
    partial void OnAKADChanging(string value);
    partial void OnAKADChanged();
    #endregion
	
	public AnaKategoriler()
	{
		this._Urunlers = new EntitySet<Urunler>(new Action<Urunler>(this.attach_Urunlers), new Action<Urunler>(this.detach_Urunlers));
		this._AltKategorilers = new EntitySet<AltKategoriler>(new Action<AltKategoriler>(this.attach_AltKategorilers), new Action<AltKategoriler>(this.detach_AltKategorilers));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int AKID
	{
		get
		{
			return this._AKID;
		}
		set
		{
			if ((this._AKID != value))
			{
				this.OnAKIDChanging(value);
				this.SendPropertyChanging();
				this._AKID = value;
				this.SendPropertyChanged("AKID");
				this.OnAKIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKAD", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string AKAD
	{
		get
		{
			return this._AKAD;
		}
		set
		{
			if ((this._AKAD != value))
			{
				this.OnAKADChanging(value);
				this.SendPropertyChanging();
				this._AKAD = value;
				this.SendPropertyChanged("AKAD");
				this.OnAKADChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AnaKategoriler_Urunler", Storage="_Urunlers", ThisKey="AKID", OtherKey="AKID")]
	public EntitySet<Urunler> Urunlers
	{
		get
		{
			return this._Urunlers;
		}
		set
		{
			this._Urunlers.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AnaKategoriler_AltKategoriler", Storage="_AltKategorilers", ThisKey="AKID", OtherKey="AKID")]
	public EntitySet<AltKategoriler> AltKategorilers
	{
		get
		{
			return this._AltKategorilers;
		}
		set
		{
			this._AltKategorilers.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Urunlers(Urunler entity)
	{
		this.SendPropertyChanging();
		entity.AnaKategoriler = this;
	}
	
	private void detach_Urunlers(Urunler entity)
	{
		this.SendPropertyChanging();
		entity.AnaKategoriler = null;
	}
	
	private void attach_AltKategorilers(AltKategoriler entity)
	{
		this.SendPropertyChanging();
		entity.AnaKategoriler = this;
	}
	
	private void detach_AltKategorilers(AltKategoriler entity)
	{
		this.SendPropertyChanging();
		entity.AnaKategoriler = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AltKategoriler")]
public partial class AltKategoriler : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ALTID;
	
	private string _ALTAD;
	
	private int _AKID;
	
	private EntitySet<Urunler> _Urunlers;
	
	private EntitySet<Markalar> _Markalars;
	
	private EntityRef<AnaKategoriler> _AnaKategoriler;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnALTIDChanging(int value);
    partial void OnALTIDChanged();
    partial void OnALTADChanging(string value);
    partial void OnALTADChanged();
    partial void OnAKIDChanging(int value);
    partial void OnAKIDChanged();
    #endregion
	
	public AltKategoriler()
	{
		this._Urunlers = new EntitySet<Urunler>(new Action<Urunler>(this.attach_Urunlers), new Action<Urunler>(this.detach_Urunlers));
		this._Markalars = new EntitySet<Markalar>(new Action<Markalar>(this.attach_Markalars), new Action<Markalar>(this.detach_Markalars));
		this._AnaKategoriler = default(EntityRef<AnaKategoriler>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ALTID
	{
		get
		{
			return this._ALTID;
		}
		set
		{
			if ((this._ALTID != value))
			{
				this.OnALTIDChanging(value);
				this.SendPropertyChanging();
				this._ALTID = value;
				this.SendPropertyChanged("ALTID");
				this.OnALTIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTAD", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string ALTAD
	{
		get
		{
			return this._ALTAD;
		}
		set
		{
			if ((this._ALTAD != value))
			{
				this.OnALTADChanging(value);
				this.SendPropertyChanging();
				this._ALTAD = value;
				this.SendPropertyChanged("ALTAD");
				this.OnALTADChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKID", DbType="Int NOT NULL")]
	public int AKID
	{
		get
		{
			return this._AKID;
		}
		set
		{
			if ((this._AKID != value))
			{
				if (this._AnaKategoriler.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnAKIDChanging(value);
				this.SendPropertyChanging();
				this._AKID = value;
				this.SendPropertyChanged("AKID");
				this.OnAKIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AltKategoriler_Urunler", Storage="_Urunlers", ThisKey="ALTID", OtherKey="ALTID")]
	public EntitySet<Urunler> Urunlers
	{
		get
		{
			return this._Urunlers;
		}
		set
		{
			this._Urunlers.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AltKategoriler_Markalar", Storage="_Markalars", ThisKey="ALTID", OtherKey="ALTID")]
	public EntitySet<Markalar> Markalars
	{
		get
		{
			return this._Markalars;
		}
		set
		{
			this._Markalars.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AnaKategoriler_AltKategoriler", Storage="_AnaKategoriler", ThisKey="AKID", OtherKey="AKID", IsForeignKey=true)]
	public AnaKategoriler AnaKategoriler
	{
		get
		{
			return this._AnaKategoriler.Entity;
		}
		set
		{
			AnaKategoriler previousValue = this._AnaKategoriler.Entity;
			if (((previousValue != value) 
						|| (this._AnaKategoriler.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._AnaKategoriler.Entity = null;
					previousValue.AltKategorilers.Remove(this);
				}
				this._AnaKategoriler.Entity = value;
				if ((value != null))
				{
					value.AltKategorilers.Add(this);
					this._AKID = value.AKID;
				}
				else
				{
					this._AKID = default(int);
				}
				this.SendPropertyChanged("AnaKategoriler");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Urunlers(Urunler entity)
	{
		this.SendPropertyChanging();
		entity.AltKategoriler = this;
	}
	
	private void detach_Urunlers(Urunler entity)
	{
		this.SendPropertyChanging();
		entity.AltKategoriler = null;
	}
	
	private void attach_Markalars(Markalar entity)
	{
		this.SendPropertyChanging();
		entity.AltKategoriler = this;
	}
	
	private void detach_Markalars(Markalar entity)
	{
		this.SendPropertyChanging();
		entity.AltKategoriler = null;
	}
}

public partial class sepetgetirResult
{
	
	private int _SepetID;
	
	private System.Nullable<int> _UyeID;
	
	private System.Nullable<int> _UrunID;
	
	private System.Nullable<System.DateTime> _EklemeTarihi;
	
	private System.Nullable<int> _Adet;
	
	public sepetgetirResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SepetID", DbType="Int NOT NULL")]
	public int SepetID
	{
		get
		{
			return this._SepetID;
		}
		set
		{
			if ((this._SepetID != value))
			{
				this._SepetID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyeID", DbType="Int")]
	public System.Nullable<int> UyeID
	{
		get
		{
			return this._UyeID;
		}
		set
		{
			if ((this._UyeID != value))
			{
				this._UyeID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunID", DbType="Int")]
	public System.Nullable<int> UrunID
	{
		get
		{
			return this._UrunID;
		}
		set
		{
			if ((this._UrunID != value))
			{
				this._UrunID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EklemeTarihi", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> EklemeTarihi
	{
		get
		{
			return this._EklemeTarihi;
		}
		set
		{
			if ((this._EklemeTarihi != value))
			{
				this._EklemeTarihi = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adet", DbType="Int")]
	public System.Nullable<int> Adet
	{
		get
		{
			return this._Adet;
		}
		set
		{
			if ((this._Adet != value))
			{
				this._Adet = value;
			}
		}
	}
}

public partial class UyeKontrolResult
{
	
	private int _UyeID;
	
	private string _UyeAdSoyad;
	
	private string _UyeEposta;
	
	private string _Sifre;
	
	private string _Adres;
	
	private string _Telefon;
	
	private string _Gsm;
	
	private System.Nullable<System.DateTime> _EklemeTarihi;
	
	private System.Nullable<int> _Onay;
	
	private string _Sehir;
	
	private string _Ilce;
	
	public UyeKontrolResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyeID", DbType="Int NOT NULL")]
	public int UyeID
	{
		get
		{
			return this._UyeID;
		}
		set
		{
			if ((this._UyeID != value))
			{
				this._UyeID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyeAdSoyad", DbType="NVarChar(100)")]
	public string UyeAdSoyad
	{
		get
		{
			return this._UyeAdSoyad;
		}
		set
		{
			if ((this._UyeAdSoyad != value))
			{
				this._UyeAdSoyad = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyeEposta", DbType="NVarChar(50)")]
	public string UyeEposta
	{
		get
		{
			return this._UyeEposta;
		}
		set
		{
			if ((this._UyeEposta != value))
			{
				this._UyeEposta = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(41)")]
	public string Sifre
	{
		get
		{
			return this._Sifre;
		}
		set
		{
			if ((this._Sifre != value))
			{
				this._Sifre = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(MAX)")]
	public string Adres
	{
		get
		{
			return this._Adres;
		}
		set
		{
			if ((this._Adres != value))
			{
				this._Adres = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="Char(11)")]
	public string Telefon
	{
		get
		{
			return this._Telefon;
		}
		set
		{
			if ((this._Telefon != value))
			{
				this._Telefon = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gsm", DbType="Char(11)")]
	public string Gsm
	{
		get
		{
			return this._Gsm;
		}
		set
		{
			if ((this._Gsm != value))
			{
				this._Gsm = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EklemeTarihi", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> EklemeTarihi
	{
		get
		{
			return this._EklemeTarihi;
		}
		set
		{
			if ((this._EklemeTarihi != value))
			{
				this._EklemeTarihi = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Onay", DbType="Int")]
	public System.Nullable<int> Onay
	{
		get
		{
			return this._Onay;
		}
		set
		{
			if ((this._Onay != value))
			{
				this._Onay = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sehir", DbType="NVarChar(50)")]
	public string Sehir
	{
		get
		{
			return this._Sehir;
		}
		set
		{
			if ((this._Sehir != value))
			{
				this._Sehir = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilce", DbType="NVarChar(50)")]
	public string Ilce
	{
		get
		{
			return this._Ilce;
		}
		set
		{
			if ((this._Ilce != value))
			{
				this._Ilce = value;
			}
		}
	}
}

public partial class UyeleriGetirResult
{
	
	private int _UyeID;
	
	private string _UyeAdSoyad;
	
	private string _UyeEposta;
	
	private string _Sifre;
	
	private string _Adres;
	
	private string _Telefon;
	
	private string _Gsm;
	
	private System.Nullable<System.DateTime> _EklemeTarihi;
	
	private System.Nullable<int> _Onay;
	
	private string _Sehir;
	
	private string _Ilce;
	
	public UyeleriGetirResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyeID", DbType="Int NOT NULL")]
	public int UyeID
	{
		get
		{
			return this._UyeID;
		}
		set
		{
			if ((this._UyeID != value))
			{
				this._UyeID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyeAdSoyad", DbType="NVarChar(100)")]
	public string UyeAdSoyad
	{
		get
		{
			return this._UyeAdSoyad;
		}
		set
		{
			if ((this._UyeAdSoyad != value))
			{
				this._UyeAdSoyad = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyeEposta", DbType="NVarChar(50)")]
	public string UyeEposta
	{
		get
		{
			return this._UyeEposta;
		}
		set
		{
			if ((this._UyeEposta != value))
			{
				this._UyeEposta = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(41)")]
	public string Sifre
	{
		get
		{
			return this._Sifre;
		}
		set
		{
			if ((this._Sifre != value))
			{
				this._Sifre = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(MAX)")]
	public string Adres
	{
		get
		{
			return this._Adres;
		}
		set
		{
			if ((this._Adres != value))
			{
				this._Adres = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="Char(11)")]
	public string Telefon
	{
		get
		{
			return this._Telefon;
		}
		set
		{
			if ((this._Telefon != value))
			{
				this._Telefon = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gsm", DbType="Char(11)")]
	public string Gsm
	{
		get
		{
			return this._Gsm;
		}
		set
		{
			if ((this._Gsm != value))
			{
				this._Gsm = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EklemeTarihi", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> EklemeTarihi
	{
		get
		{
			return this._EklemeTarihi;
		}
		set
		{
			if ((this._EklemeTarihi != value))
			{
				this._EklemeTarihi = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Onay", DbType="Int")]
	public System.Nullable<int> Onay
	{
		get
		{
			return this._Onay;
		}
		set
		{
			if ((this._Onay != value))
			{
				this._Onay = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sehir", DbType="NVarChar(50)")]
	public string Sehir
	{
		get
		{
			return this._Sehir;
		}
		set
		{
			if ((this._Sehir != value))
			{
				this._Sehir = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilce", DbType="NVarChar(50)")]
	public string Ilce
	{
		get
		{
			return this._Ilce;
		}
		set
		{
			if ((this._Ilce != value))
			{
				this._Ilce = value;
			}
		}
	}
}

public partial class VitrinGetirResult
{
	
	private int _ID;
	
	private string _VitrinResim;
	
	private string _VitrinUrl;
	
	public VitrinGetirResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VitrinResim", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string VitrinResim
	{
		get
		{
			return this._VitrinResim;
		}
		set
		{
			if ((this._VitrinResim != value))
			{
				this._VitrinResim = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VitrinUrl", DbType="NVarChar(150)")]
	public string VitrinUrl
	{
		get
		{
			return this._VitrinUrl;
		}
		set
		{
			if ((this._VitrinUrl != value))
			{
				this._VitrinUrl = value;
			}
		}
	}
}
#pragma warning restore 1591
